version: "3"

services:
  app:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        VARIANT: 14 #Update 'VARIANT' to pick a Node version: 10, 12, 14
    command: sleep infinity
    volumes:
      - ./:/workspace
